version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: mostafakamar
      POSTGRES_PASSWORD: BooKelwaa771
      POSTGRES_DB: database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://mostafakamar:BooKelwaa771@db:5432/database
    depends_on:
      - db
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
